# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Swift项目' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  pod 'SwiftyJSON'

  pod 'KakaJSON'

  pod 'SnapKit'

  pod 'Moya'

  pod 'Kingfisher'
  
  pod 'IQKeyboardManagerSwift'

  pod 'MJRefresh'
  
  pod 'SVProgressHUD'
  
  pod 'LookinServer', :configurations => ['Debug']
end
